import fs from 'fs-extra';
import path from 'path';

export async function generateReadme(projectPath: string, contractName: string) {
  const contractPath = path.join(projectPath, 'contracts', `${contractName}.sol`);
  const readmePath = path.join(projectPath, 'README.md');

  if (!fs.existsSync(contractPath)) {
    console.warn(`⚠️ Warning: Contract file not found for documentation at ${contractPath}`);
    return;
  }

  const content = fs.readFileSync(contractPath, 'utf8');
  
  // 1. Extract Title & Notice (Regex Magic)
  const titleMatch = content.match(/@title\s+(.+)/);
  const noticeMatch = content.match(/@notice\s+(.+)/);
  const title = titleMatch ? titleMatch[1] : contractName;
  const description = noticeMatch ? noticeMatch[1] : 'No description provided.';

  // 2. Generate Markdown Content
  let mdContent = `# ${title}\n\n`;
  mdContent += `> ${description}\n\n`;
  
  mdContent += `## Overview\n`;
  mdContent += `This example demonstrates FHEVM capability using **${contractName}**.\n`;
  mdContent += `It is generated automatically using the FHEVM Example Hub.\n\n`;

  mdContent += `## 🚀 How to Run\n\n`;
  mdContent += `### 1. Install Dependencies\n`;
  mdContent += `\`\`\`bash\nnpm install\n\`\`\`\n\n`;
  
  mdContent += `### 2. Run Tests\n`;
  mdContent += `\`\`\`bash\nnpx hardhat test\n\`\`\`\n\n`;

  mdContent += `## 📜 Smart Contract Logic\n`;
  mdContent += `The contract is located at \`contracts/${contractName}.sol\`.\n\n`;

  // 3. Extract Functions (Simple parser)
  mdContent += `### Key Functions\n`;
  const lines = content.split('\n');
  lines.forEach((line, index) => {
    if (line.trim().startsWith('function')) {
      // Look back for @notice
      let docComment = '';
      if (index > 0 && lines[index-1].includes('@notice')) {
        docComment = lines[index-1].replace(/.*@notice\s+/, '').trim();
      }
      
      const funcSig = line.split('{')[0].trim();
      mdContent += `- \`${funcSig}\`\n`;
      if (docComment) {
        mdContent += `  - *${docComment}*\n`;
      }
    }
  });

  mdContent += `\n---\n*Generated by FHEVM Example Hub*`;

  // 4. Write File
  fs.writeFileSync(readmePath, mdContent);
  console.log('📝 Documentation (README.md) generated successfully.');
}